SELECT ACCT_ID  
FROM
  (SELECT ACCT_ID,
    SUM(CASH_ONLY_PTS) CASH_ONLY_PTS
  FROM CI_ACCT_CR_R_VW
  GROUP BY ACCT_ID
  ) ACCT_CR_DATA,
  (SELECT START_CASH_ONL_PTS,CASH_ONLY_PTS_THRS FROM C0_INSTALLATION
  ) INST_DATA
WHERE (CASH_ONLY_PTS+START_CASH_ONL_PTS) > CASH_ONLY_PTS_THRS;
